### ISSUE TITLE
How to run an installed gem?

### ISSUE THREAD

**Issue by robross0606** [stephan-nordnes-eriksen/ruby_ship#12]
I successfully installed a gem using ruby_ship_gem.bat, but how can it be executed without changing the PATH?

**Comment by stephan-nordnes-eriksen** [comment]
Not sure I understand what you mean. What are you trying to do?

**Comment by robross0606** [comment]
Nevermind, I figured it out.  The installed gems create .bat files under win_ruby.  Just had to adjust the PATH to find them.

**Comment by stephan-nordnes-eriksen** [comment]
Gems installing native plugins can sometimes be troublesome on windows. You might have to change the wrappers to make it work properly. Unfortunately the windows support is not 100% solid in ruby_ship. I believe it is explained in the readme.

**Comment by robross0606** [comment]
It works fine once I added ruby_win32\bin to the PATH.
